// <auto-generated />
using System;
using DomainModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DomainModels.Migrations
{
    [DbContext(typeof(OrderDbContext))]
    [Migration("20200120131202_inti")]
    partial class inti
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DomainModels.OrderDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateCreated");

                    b.Property<DateTime>("DeliveryDate");

                    b.Property<int>("DeliveryStatus");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("ProductDescription");

                    b.HasKey("Id");

                    b.ToTable("Orders");

                    b.HasData(
                        new { Id = 1, DateCreated = new DateTime(2020, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified), DeliveryDate = new DateTime(2020, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified), DeliveryStatus = 3, IsDeleted = false, ProductDescription = "Large Pizza with CocaCola" },
                        new { Id = 2, DateCreated = new DateTime(2020, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified), DeliveryDate = new DateTime(2020, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified), DeliveryStatus = 3, IsDeleted = false, ProductDescription = "Large Pizza with CocaCola" },
                        new { Id = 3, DateCreated = new DateTime(2020, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), DeliveryDate = new DateTime(2020, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), DeliveryStatus = 2, IsDeleted = false, ProductDescription = "Large Pizza with CocaCola" },
                        new { Id = 4, DateCreated = new DateTime(2020, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified), DeliveryDate = new DateTime(2020, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified), DeliveryStatus = 1, IsDeleted = false, ProductDescription = "Large Pizza with CocaCola" }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
